# Generated by Django 3.1.2 on 2020-10-02 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splitter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='tip',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15),
        ),
    ]
