# Generated by Django 3.1.2 on 2020-10-08 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splitter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
