# Generated by Django 3.1.2 on 2020-10-02 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splitter', '0002_auto_20201001_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='tax',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='bill',
            name='tip',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15),
        ),
    ]
