# Generated by Django 3.1.2 on 2020-10-09 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splitter', '0003_auto_20201007_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='tax',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='tip',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True),
        ),
    ]
