# Generated by Django 3.1.2 on 2020-10-02 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('splitter', '0003_auto_20201001_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='bill',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bill', to='splitter.bill'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='shared',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='person', to='splitter.person'),
        ),
    ]
