# Generated by Django 3.1.2 on 2020-10-09 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('splitter', '0004_auto_20201008_2206'),
        ('splitter', '0004_auto_20201009_1430'),
    ]

    operations = [
    ]
