# Generated by Django 3.1.2 on 2020-10-09 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splitter', '0006_auto_20201009_1603'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['id'], name='item_id_index'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['id'], name='person_id_index'),
        ),
    ]
