# Generated by Django 3.1.2 on 2020-10-12 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('splitter', '0008_auto_20201011_1907'),
        ('splitter', '0008_auto_20201011_0301'),
    ]

    operations = [
    ]
