# Generated by Django 3.1.2 on 2020-10-12 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splitter', '0009_merge_20201012_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='tax_percent',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
    ]
