# Generated by Django 3.1.2 on 2020-10-16 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splitter', '0011_bill_tip_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='session',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
